DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE YNDEDUCATION CASCADE CONSTRAINTS;
DROP TABLE YNDRECORD CASCADE CONSTRAINTS;
DROP TABLE YNDWORD CASCADE CONSTRAINTS;
DROP TABLE YNDVOCA CASCADE CONSTRAINTS;

DROP SEQUENCE ID_SEQ
DROP SEQUENCE EDU_SEQ
DROP SEQUENCE REC_SEQ
DROP SEQUENCE WOR_SEQ
DROP SEQUENCE VOC_SEQ

CREATE SEQUENCE ID_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE EDU_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE REC_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE WOR_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE VOC_SEQ START WITH 1 INCREMENT BY 1

CREATE TABLE MEMBER(
	IDNUM NUMBER NOT NULL,
	ID VARCHAR2(200) NOT NULL,
	PW VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	TEL VARCHAR2(200) NOT NULL,
	GENDER VARCHAR2(200) NOT NULL,
	CONSTRAINT MEMBER_PK123 PRIMARY KEY (IDNUM)
	)
	
CREATE TABLE YNDVOCA(
	VOCANUM NUMBER NOT NULL,
	VOCA VARCHAR2(1000 BYTE) NOT NULL,
	CONSTRAINT YNDVOCA_PK PRIMARY KEY (VOCANUM)
	)
	
CREATE TABLE YNDRECORD(
	RECORDNUM NUMBER NOT NULL,
	RECORD VARCHAR2(1000 BYTE) NOT NULL,
	VOCANUM NUMBER NOT NULL,
	RECORDDATE DATE NOT NULL,
	IDNUM NUMBER NOT NULL,
	CONSTRAINT YNDRECORD_PK PRIMARY KEY (RECORDNUM),
	CONSTRAINT YNDRECORD_FK26 FOREIGN KEY (VOCANUM) REFERENCES YNDVOCA (VOCANUM),
	CONSTRAINT YNDRECORD_FK22 FOREIGN KEY (IDNUM) REFERENCES MEMBER (IDNUM)
	)
   
CREATE TABLE YNDEDUCATION(
	EDUNUM NUMBER NOT NULL,
	WORD1 NUMBER NOT NULL,
	WORD2 NUMBER NOT NULL,
	WORD3 NUMBER NOT NULL,
	SENTENCE1 NUMBER NOT NULL,
	SENTENCE2 NUMBER NOT NULL,
	ALLSIM NUMBER NOT NULL,
	UK NUMBER NOT NULL,
	US NUMBER NOT NULL,
	IDNUM number NOT NULL,
	RECORDNUM NUMBER NOT NULL,
	CONSTRAINT YNDEDUCATION_PK PRIMARY KEY (EDUNUM),
	CONSTRAINT YNDEDUCATION_FK5 FOREIGN KEY (RECORDNUM) REFERENCES YNDRECORD (RECORDNUM),
	CONSTRAINT YNDEDUCATION_FK9 FOREIGN KEY (IDNUM) REFERENCES MEMBER (IDNUM)
    )
    
CREATE TABLE YNDWORD(
	WORDNUM NUMBER NOT NULL,
	WORD VARCHAR2(1000 BYTE) NOT NULL,
	EDUNUM NUMBER NOT NULL,
	CONSTRAINT YNDWORD_PK PRIMARY KEY (WORDNUM),
	CONSTRAINT YNDWORD_FK1 FOREIGN KEY (EDUNUM) REFERENCES YNDEDUCATION (EDUNUM)
	)
	
INSERT INTO YNDVOCA VALUES (VOC_SEQ.NEXTVAL,'sick')
INSERT INTO YNDVOCA VALUES (VOC_SEQ.NEXTVAL,'thick')
INSERT INTO YNDVOCA VALUES (VOC_SEQ.NEXTVAL,'chic')
INSERT INTO YNDVOCA VALUES (VOC_SEQ.NEXTVAL,'she wears thick and chic shoes eventhough she is sick')
INSERT INTO YNDVOCA VALUES (VOC_SEQ.NEXTVAL,'i can see many trees thick with leaves around the park')

SELECT * FROM MEMBER
SELECT * FROM YNDEDUCATION
SELECT * FROM YNDRECORD
SELECT * FROM YNDWORD
SELECT * FROM YNDVOCA
