DROP TABLE MEMBER CASCADE CONSTRAINTS
DROP TABLE YNDEDUCATION CASCADE CONSTRAINTS
DROP TABLE YNDEDUHISTORY CASCADE CONSTRAINTS
DROP TABLE YNDRECORD CASCADE CONSTRAINTS
DROP TABLE YNDWORD CASCADE CONSTRAINTS

DROP SEQUENCE ID_SEQ
DROP SEQUENCE EDU_SEQ
DROP SEQUENCE HIS_SEQ
DROP SEQUENCE REC_SEQ
DROP SEQUENCE WOR_SEQ

CREATE SEQUENCE ID_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE EDU_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE HIS_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE REC_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE WOR_SEQ START WITH 1 INCREMENT BY 1

CREATE TABLE MEMBER(
	IDNUM NUMBER NOT NULL,
	ID VARCHAR2(200) NOT NULL,
	PW VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	TEL VARCHAR2(200) NOT NULL,
	GENDER VARCHAR2(200) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY (IDNUM)
	)
	
CREATE TABLE YNDWORD(
	WORDNUM NUMBER NOT NULL,
	WORD VARCHAR2(1000 BYTE) NOT NULL,
    CONSTRAINT YNDWORD_PK PRIMARY KEY (WORDNUM)
    )
    
CREATE TABLE YNDRECORD(
	RECORDNUM NUMBER NOT NULL,
	RECORD VARCHAR2(1000 BYTE) NOT NULL,
	WORDNUM NUMBER NOT NULL,
	RECORDDATE DATE NOT NULL,
    CONSTRAINT YNDRECORD_PK PRIMARY KEY (RECORDNUM),
    CONSTRAINT YNDRECORD_FK2 FOREIGN KEY (WORDNUM) REFERENCES YNDWORD (WORDNUM) 
   )
   
CREATE TABLE YNDEDUCATION(
	EDUNUM NUMBER NOT NULL,
	WORD1 NUMBER NOT NULL,
	WORD2 NUMBER NOT NULL,
	ORD3 NUMBER NOT NULL,
	SENTENCE1 NUMBER NOT NULL,
	SENTENCE2 NUMBER NOT NULL,
	ALLSIM NUMBER NOT NULL,
	UK NUMBER NOT NULL,
	US NUMBER NOT NULL,
	IDNUM NUMBER NOT NULL,
	RECORDNUM NUMBER NOT NULL,
    CONSTRAINT YNDEDUCATION_PK PRIMARY KEY (EDUNUM),
    CONSTRAINT YNDEDUCATION_FK5 FOREIGN KEY (RECORDNUM) REFERENCES YNDRECORD (RECORDNUM),
    CONSTRAINT YNDEDUCATION_FK4 FOREIGN KEY (IDNUM) REFERENCES MEMBER (IDNUM)
    )

CREATE TABLE YNDEDUHISTORY(
	HISTORYNUM NUMBER NOT NULL,
	EDUNUM NUMBER NOT NULL,
	CONSTRAINT YNDEDUHISTORY_PK PRIMARY KEY (HISTORYNUM),
	CONSTRAINT YNDEDUHISTORY_FK2 FOREIGN KEY (EDUNUM) REFERENCES YNDEDUCATION (EDUNUM)
	)
	
INSERT INTO YNDWORD VALUES (WOR_SEQ.nextval,'sick')
INSERT INTO YNDWORD VALUES (WOR_SEQ.nextval,'thick')
INSERT INTO YNDWORD VALUES (WOR_SEQ.nextval,'chic')
INSERT INTO YNDWORD VALUES (WOR_SEQ.nextval,'she wear thick and chic shoes eventhough she is sick')
INSERT INTO YNDWORD VALUES (WOR_SEQ.nextval,'i can see many trees thick with leaves around the park')

	
SELECT * FROM MEMBER
SELECT * FROM YNDEDUCATION
SELECT * FROM YNDEDUHISTORY
SELECT * FROM YNDRECORD
SELECT * FROM YNDWORD